import {unpackFormArray} from '../src/utils';

describe('unpackFormArray', () => {
    test('unpack', () => {
        const input = {
            '0': {completed: true},
            '1': {completed: true},
            '2': {completed: true},
            '3': {completed: false},
            '4': {completed: false},
            '5': {completed: false},
            '6': {completed: false},
            '7': {completed: false},
            '8': {completed: false},
            '9': {completed: false},
            '10': {complete: false},
            '11': {complete: false},
            '12': {complete: false},
            '13': {complete: false},
            '14': {complete: false},
            '15': {complete: false},
            '16': {complete: false},
            '17': {complete: false},
            '18': {complete: false},
            '19': {complete: false},
            '20': {complete: false},
            '21': {complete: false},
            '22': {complete: false},
            '23': {complete: false},
            '24': {complete: false},
            '25': {complete: false},
            '26': {complete: false},
            '27': {complete: false},
            '28': {complete: false},
            '29': {complete: false},
            '30': {complete: false},
            '31': {complete: false},
            '32': {complete: false},
            '33': {complete: false},
            '34': {complete: false},
            '35': {complete: false},
        };
        expect(unpackFormArray(input)).toEqual([
            {completed: true},
            {completed: true},
            {completed: true},
            {completed: false},
            {completed: false},
            {completed: false},
            {completed: false},
            {completed: false},
            {completed: false},
            {completed: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
            {complete: false},
        ]);
    });
});
